### ISSUE TITLE
Where did you acquire games.txt

### ISSUE THREAD

**Issue by ghost** [nikop/SteamControllerConfigDownloader#2]
Apologies for the off-topic issue, but I'm need of such a list for one of my own projects and I'd like to be able to keep it updated myself. I am aware of http://api.steampowered.com/ISteamApps/GetAppList/v0002/ though that returns more than just games. I've also tried to get SteamDatabaseBackend working, but it seems that Valve has blocked their full run so I can't do much with their either.

Any advice would be much appreciated.

**Comment by nikop** [comment]
It uses same method as SteamDatabase does. Best option is probably to wait Valve to fix it.
